[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 895733145247289355
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 16

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Forging your instance"
	#The second line of text under the app name
	state = "Düncraft Reborn is starting..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[init.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[init.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is asleep in the tavern"
	#The second line of text under the app name
	state = "Idle in the main menu"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[main_menu.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[main_menu.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[server_list.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[server_list.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = false
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	buttons = []

[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is exiting the tavern"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[join_game.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[join_game.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently In %world%"
	#The second line of text under the app name
	state = "Mining solo"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[single_player.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[single_player.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Exploring with %players% dwarves"
	#The second line of text under the app name
	state = "Mining together"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[multi_player.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[multi_player.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = false
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	buttons = []

[generic]
	#The first line of text under the app name
	description = "Playing Düncraft Reborn"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = "duncraft512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dünhold's official Minecraft modpack "
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = "forge512"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	[[generic.buttons]]
		label = "Get the latest build"
		url = "https://discord.com/channels/660941131827380254/1028419807944650784"

	[[generic.buttons]]
		label = "Report a bug/request a feature"
		url = "https://discord.com/channels/660941131827380254/917643066163204096/1012080129503146095"


[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"
		buttons = []


